export const psgSchedule2627 = [
  { round: 1, isoDate: "2026-08-23", day: "dimanche", dateLabel: "23 août 2026", month: "2026-08", competition: "Ligue 1", home: "Paris Saint-Germain", away: "Stade Rennais", opponent: "Stade Rennais", venue: "Parc des Princes", place: "Domicile", time: "20:45", status: "Programmé", note: "Ouverture de saison au Parc.", highlight: true },
  { round: 2, isoDate: "2026-08-28", day: "vendredi", dateLabel: "28 août 2026", month: "2026-08", competition: "Ligue 1", home: "LOSC", away: "Paris Saint-Germain", opponent: "LOSC", venue: "Decathlon Arena - Stade Pierre-Mauroy", place: "Extérieur", time: "20:45", status: "Programmé", note: "Premier déplacement dense de la saison.", highlight: false },
  { round: 3, isoDate: "2026-09-05", day: "samedi", dateLabel: "5 septembre 2026", month: "2026-09", competition: "Ligue 1", home: "Paris Saint-Germain", away: "AS Monaco", opponent: "AS Monaco", venue: "Parc des Princes", place: "Domicile", time: "À confirmer", status: "Horaire à confirmer", note: "Affiche directe entre prétendants au podium.", highlight: true },
  { round: 4, isoDate: "2026-09-12", day: "samedi", dateLabel: "12 septembre 2026", month: "2026-09", competition: "Ligue 1", home: "Stade Brestois 29", away: "Paris Saint-Germain", opponent: "Stade Brestois 29", venue: "Stade Francis-Le Blé", place: "Extérieur", time: "À confirmer", status: "Horaire à confirmer", note: "Déplacement piège après la trêve.", highlight: false },
  { round: 5, isoDate: "2026-09-20", day: "dimanche", dateLabel: "20 septembre 2026", month: "2026-09", competition: "Ligue 1", home: "Olympique de Marseille", away: "Paris Saint-Germain", opponent: "Olympique de Marseille", venue: "Orange Vélodrome", place: "Extérieur", time: "20:45", status: "Programmé", note: "Premier Classique de la saison.", highlight: true },
  { round: 6, isoDate: "2026-10-10", day: "samedi", dateLabel: "10 octobre 2026", month: "2026-10", competition: "Ligue 1", home: "Paris Saint-Germain", away: "Le Mans FC", opponent: "Le Mans FC", venue: "Parc des Princes", place: "Domicile", time: "À confirmer", status: "Horaire à confirmer", note: "Retour au Parc contre un promu ambitieux.", highlight: false },
  { round: 7, isoDate: "2026-10-17", day: "samedi", dateLabel: "17 octobre 2026", month: "2026-10", competition: "Ligue 1", home: "RC Strasbourg", away: "Paris Saint-Germain", opponent: "RC Strasbourg", venue: "Stade de la Meinau", place: "Extérieur", time: "À confirmer", status: "Horaire à confirmer", note: "La Meinau, toujours électrique.", highlight: false },
  { round: 8, isoDate: "2026-10-25", day: "dimanche", dateLabel: "25 octobre 2026", month: "2026-10", competition: "Ligue 1", home: "Paris Saint-Germain", away: "Olympique Lyonnais", opponent: "Olympique Lyonnais", venue: "Parc des Princes", place: "Domicile", time: "20:45", status: "Programmé", note: "Choc historique du championnat.", highlight: true },
  { round: 9, isoDate: "2026-10-31", day: "samedi", dateLabel: "31 octobre 2026", month: "2026-10", competition: "Ligue 1", home: "Le Havre AC", away: "Paris Saint-Germain", opponent: "Le Havre AC", venue: "Stade Océane", place: "Extérieur", time: "À confirmer", status: "Horaire à confirmer", note: "Match à gérer sans tomber dans le confort.", highlight: false },
  { round: 10, isoDate: "2026-11-07", day: "samedi", dateLabel: "7 novembre 2026", month: "2026-11", competition: "Ligue 1", home: "Paris Saint-Germain", away: "ESTAC Troyes", opponent: "ESTAC Troyes", venue: "Parc des Princes", place: "Domicile", time: "À confirmer", status: "Horaire à confirmer", note: "Paris doit imposer son tempo.", highlight: false },
  { round: 11, isoDate: "2026-11-21", day: "samedi", dateLabel: "21 novembre 2026", month: "2026-11", competition: "Ligue 1", home: "OGC Nice", away: "Paris Saint-Germain", opponent: "OGC Nice", venue: "Allianz Riviera", place: "Extérieur", time: "À confirmer", status: "Horaire à confirmer", note: "Duel tactique contre un adversaire souvent pénible.", highlight: true },
  { round: 12, isoDate: "2026-11-28", day: "samedi", dateLabel: "28 novembre 2026", month: "2026-11", competition: "Ligue 1", home: "Paris Saint-Germain", away: "FC Lorient", opponent: "FC Lorient", venue: "Parc des Princes", place: "Domicile", time: "À confirmer", status: "Horaire à confirmer", note: "Match de contrôle attendu au Parc.", highlight: false },
  { round: 13, isoDate: "2026-12-05", day: "samedi", dateLabel: "5 décembre 2026", month: "2026-12", competition: "Ligue 1", home: "Toulouse FC", away: "Paris Saint-Germain", opponent: "Toulouse FC", venue: "Stadium de Toulouse", place: "Extérieur", time: "À confirmer", status: "Horaire à confirmer", note: "Déplacement sud-ouest avant l'emballage de décembre.", highlight: false },
  { round: 14, isoDate: "2026-12-12", day: "samedi", dateLabel: "12 décembre 2026", month: "2026-12", competition: "Ligue 1", home: "Paris Saint-Germain", away: "Paris FC", opponent: "Paris FC", venue: "Parc des Princes", place: "Domicile", time: "À confirmer", status: "Horaire à confirmer", note: "Derby parisien au Parc.", highlight: true },
  { round: 15, isoDate: "2027-01-03", day: "dimanche", dateLabel: "3 janvier 2027", month: "2027-01", competition: "Ligue 1", home: "Racing Club de Lens", away: "Paris Saint-Germain", opponent: "RC Lens", venue: "Stade Bollaert-Delelis", place: "Extérieur", time: "20:45", status: "Programmé", note: "Reprise intense à Bollaert.", highlight: true },
  { round: 16, isoDate: "2027-01-16", day: "samedi", dateLabel: "16 janvier 2027", month: "2027-01", competition: "Ligue 1", home: "Angers SCO", away: "Paris Saint-Germain", opponent: "Angers SCO", venue: "Stade Raymond Kopa", place: "Extérieur", time: "À confirmer", status: "Horaire à confirmer", note: "Un match de janvier à gagner sans bruit.", highlight: false },
  { round: 17, isoDate: "2027-01-23", day: "samedi", dateLabel: "23 janvier 2027", month: "2027-01", competition: "Ligue 1", home: "Paris Saint-Germain", away: "AJ Auxerre", opponent: "AJ Auxerre", venue: "Parc des Princes", place: "Domicile", time: "À confirmer", status: "Horaire à confirmer", note: "Fin de phase aller au Parc.", highlight: false },
  { round: 18, isoDate: "2027-01-30", day: "samedi", dateLabel: "30 janvier 2027", month: "2027-01", competition: "Ligue 1", home: "AS Monaco", away: "Paris Saint-Germain", opponent: "AS Monaco", venue: "Stade Louis-II", place: "Extérieur", time: "À confirmer", status: "Horaire à confirmer", note: "Le déplacement qui teste une saison.", highlight: true },
  { round: 19, isoDate: "2027-02-07", day: "dimanche", dateLabel: "7 février 2027", month: "2027-02", competition: "Ligue 1", home: "Paris Saint-Germain", away: "Olympique de Marseille", opponent: "Olympique de Marseille", venue: "Parc des Princes", place: "Domicile", time: "20:45", status: "Programmé", note: "Classique retour, atmosphère garantie.", highlight: true },
  { round: 20, isoDate: "2027-02-13", day: "samedi", dateLabel: "13 février 2027", month: "2027-02", competition: "Ligue 1", home: "Le Mans FC", away: "Paris Saint-Germain", opponent: "Le Mans FC", venue: "Stade Marie-Marvingt", place: "Extérieur", time: "À confirmer", status: "Horaire à confirmer", note: "Déplacement à ne pas banaliser.", highlight: false },
  { round: 21, isoDate: "2027-02-20", day: "samedi", dateLabel: "20 février 2027", month: "2027-02", competition: "Ligue 1", home: "Paris Saint-Germain", away: "Stade Brestois 29", opponent: "Stade Brestois 29", venue: "Parc des Princes", place: "Domicile", time: "À confirmer", status: "Horaire à confirmer", note: "Retour au Parc avant une affiche européenne possible.", highlight: false },
  { round: 22, isoDate: "2027-02-28", day: "dimanche", dateLabel: "28 février 2027", month: "2027-02", competition: "Ligue 1", home: "Paris Saint-Germain", away: "Racing Club de Lens", opponent: "RC Lens", venue: "Parc des Princes", place: "Domicile", time: "20:45", status: "Programmé", note: "Lens au Parc, duel de haute intensité.", highlight: true },
  { round: 23, isoDate: "2027-03-06", day: "samedi", dateLabel: "6 mars 2027", month: "2027-03", competition: "Ligue 1", home: "Stade Rennais", away: "Paris Saint-Germain", opponent: "Stade Rennais", venue: "Roazhon Park", place: "Extérieur", time: "À confirmer", status: "Horaire à confirmer", note: "Rennes reste un test de concentration.", highlight: false },
  { round: 24, isoDate: "2027-03-13", day: "samedi", dateLabel: "13 mars 2027", month: "2027-03", competition: "Ligue 1", home: "AJ Auxerre", away: "Paris Saint-Germain", opponent: "AJ Auxerre", venue: "Stade de l'Abbé Deschamps", place: "Extérieur", time: "À confirmer", status: "Horaire à confirmer", note: "Match de gestion dans le sprint de printemps.", highlight: false },
  { round: 25, isoDate: "2027-03-20", day: "samedi", dateLabel: "20 mars 2027", month: "2027-03", competition: "Ligue 1", home: "Paris Saint-Germain", away: "RC Strasbourg", opponent: "RC Strasbourg", venue: "Parc des Princes", place: "Domicile", time: "À confirmer", status: "Horaire à confirmer", note: "Dernier match avant avril, période charnière.", highlight: false },
  { round: 26, isoDate: "2027-04-03", day: "samedi", dateLabel: "3 avril 2027", month: "2027-04", competition: "Ligue 1", home: "Paris FC", away: "Paris Saint-Germain", opponent: "Paris FC", venue: "Stade Jean Bouin", place: "Extérieur", time: "À confirmer", status: "Horaire à confirmer", note: "Derby parisien version Jean Bouin.", highlight: true },
  { round: 27, isoDate: "2027-04-10", day: "samedi", dateLabel: "10 avril 2027", month: "2027-04", competition: "Ligue 1", home: "Paris Saint-Germain", away: "Le Havre AC", opponent: "Le Havre AC", venue: "Parc des Princes", place: "Domicile", time: "À confirmer", status: "Horaire à confirmer", note: "Le genre de match où la rotation compte.", highlight: false },
  { round: 28, isoDate: "2027-04-17", day: "samedi", dateLabel: "17 avril 2027", month: "2027-04", competition: "Ligue 1", home: "Paris Saint-Germain", away: "LOSC", opponent: "LOSC", venue: "Parc des Princes", place: "Domicile", time: "À confirmer", status: "Horaire à confirmer", note: "Lille au Parc, match à fort coefficient tactique.", highlight: true },
  { round: 29, isoDate: "2027-04-24", day: "samedi", dateLabel: "24 avril 2027", month: "2027-04", competition: "Ligue 1", home: "FC Lorient", away: "Paris Saint-Germain", opponent: "FC Lorient", venue: "Stade du Moustoir - Yves Allainmat", place: "Extérieur", time: "À confirmer", status: "Horaire à confirmer", note: "Déplacement breton dans le money-time.", highlight: false },
  { round: 30, isoDate: "2027-05-01", day: "samedi", dateLabel: "1 mai 2027", month: "2027-05", competition: "Ligue 1", home: "Paris Saint-Germain", away: "Angers SCO", opponent: "Angers SCO", venue: "Parc des Princes", place: "Domicile", time: "À confirmer", status: "Horaire à confirmer", note: "Paris doit convertir ce type d'affiche.", highlight: false },
  { round: 31, isoDate: "2027-05-09", day: "dimanche", dateLabel: "9 mai 2027", month: "2027-05", competition: "Ligue 1", home: "Olympique Lyonnais", away: "Paris Saint-Germain", opponent: "Olympique Lyonnais", venue: "Groupama Stadium", place: "Extérieur", time: "20:45", status: "Programmé", note: "Lyon-PSG à trois journées de la fin.", highlight: true },
  { round: 32, isoDate: "2027-05-16", day: "dimanche", dateLabel: "16 mai 2027", month: "2027-05", competition: "Ligue 1", home: "Paris Saint-Germain", away: "OGC Nice", opponent: "OGC Nice", venue: "Parc des Princes", place: "Domicile", time: "À confirmer", status: "Horaire à confirmer", note: "Dernière grosse réception potentielle.", highlight: true },
  { round: 33, isoDate: "2027-05-22", day: "samedi", dateLabel: "22 mai 2027", month: "2027-05", competition: "Ligue 1", home: "ESTAC Troyes", away: "Paris Saint-Germain", opponent: "ESTAC Troyes", venue: "Stade de l'Aube", place: "Extérieur", time: "À confirmer", status: "Horaire à confirmer", note: "Avant-dernière journée, chaque détail peut compter.", highlight: false },
  { round: 34, isoDate: "2027-05-29", day: "samedi", dateLabel: "29 mai 2027", month: "2027-05", competition: "Ligue 1", home: "Paris Saint-Germain", away: "Toulouse FC", opponent: "Toulouse FC", venue: "Parc des Princes", place: "Domicile", time: "À confirmer", status: "Horaire à confirmer", note: "Clôture officielle au Parc.", highlight: true }
];

export const currentPlayerProfiles = [
  { id: "alessandro-longoni", name: "Alessandro Longoni", number: "16", position: "Gardien de but", line: "Gardiens", status: "Effectif provisoire PSG 2026-2027", role: "Gardien de rotation", profile: "Profil jeune à développer dans un environnement très exposé.", watch: "Temps de jeu, intégration aux entraînements de Luis Enrique, hiérarchie des gardiens.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "lucas-chevalier", name: "Lucas Chevalier", number: "30", position: "Gardien de but", line: "Gardiens", status: "Effectif provisoire PSG 2026-2027", role: "Gardien français à fort potentiel", profile: "Lecture moderne du poste, jeu au pied et capacité à vivre loin de sa ligne.", watch: "Concurrence avec Safonov, place dans les grands matchs, adaptation à la pression parisienne.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "matvey-safonov", name: "Matvey Safonov", number: "39", position: "Gardien de but", line: "Gardiens", status: "Effectif provisoire PSG 2026-2027", role: "Gardien confirmé", profile: "Gardien robuste, utile dans une saison à haute densité.", watch: "Gestion de la concurrence et fiabilité sur les matchs à élimination.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "achraf-hakimi", name: "Achraf Hakimi", number: "2", position: "Défenseur", line: "Défenseurs", status: "Cadre majeur", role: "Latéral droit offensif", profile: "Accélération, volume et projection : l'un des moteurs du PSG moderne.", watch: "Son entente avec l'ailier droit et son impact dans les affiches européennes.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "lucas-beraldo", name: "Lucas Beraldo", number: "4", position: "Défenseur", line: "Défenseurs", status: "Rotation premium", role: "Défenseur central gaucher", profile: "Relance propre, calme sous pression et marge de progression encore réelle.", watch: "Minutes gagnées face à la concurrence centrale.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "marquinhos", name: "Marquinhos", number: "5", position: "Défenseur", line: "Défenseurs", status: "Capitaine et recordman", role: "Défenseur central, leader de vestiaire", profile: "Repère historique du groupe, symbole de continuité entre plusieurs cycles parisiens.", watch: "Gestion physique et rôle dans une défense rajeunie.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "illia-zabarnyi", name: "Illia Zabarnyi", number: "6", position: "Défenseur", line: "Défenseurs", status: "Effectif provisoire PSG 2026-2027", role: "Défenseur central", profile: "Profil de duel, concentration et défense de surface.", watch: "Adaptation à la ligne haute parisienne.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "lucas-hernandez", name: "Lucas Hernández", number: "21", position: "Défenseur", line: "Défenseurs", status: "Cadre polyvalent", role: "Défenseur central ou latéral gauche", profile: "Intensité, agressivité positive et culture des matchs sous tension.", watch: "Disponibilité physique, rôle derrière Nuno Mendes et en axe gauche.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "nuno-mendes", name: "Nuno Mendes", number: "25", position: "Défenseur", line: "Défenseurs", status: "Titulaire majeur", role: "Latéral gauche explosif", profile: "Vitesse, percussion et capacité à casser les blocs sur un appui.", watch: "Gestion physique et connexion avec Barcola ou Kvaratskhelia.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "willian-pacho", name: "Willian Pacho", number: "51", position: "Défenseur", line: "Défenseurs", status: "Défenseur de référence", role: "Défenseur central gaucher", profile: "Volume défensif, couverture et sérénité dans une équipe qui attaque beaucoup.", watch: "Leadership dans les matchs fermés.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "fabian-ruiz", name: "Fabián Ruiz", number: "8", position: "Milieu de terrain", line: "Milieux", status: "Cadre technique", role: "Milieu relayeur", profile: "Contrôle, orientation et frappe : il donne de la respiration au jeu parisien.", watch: "Forme post-Coupe du monde et rôle dans les grandes affiches.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "vitinha", name: "Vitinha", number: "17", position: "Milieu de terrain", line: "Milieux", status: "Cerveau du jeu", role: "Milieu organisateur", profile: "Le joueur qui règle le tempo, résiste au pressing et accélère quand Paris veut étouffer.", watch: "Influence dans les matchs verrouillés.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "kang-in-lee", name: "Kang-In Lee", number: "19", position: "Milieu de terrain", line: "Milieux", status: "Profil créatif", role: "Milieu offensif ou relayeur", profile: "Pied gauche, conservation et passes dans les petits espaces.", watch: "Temps de jeu dans un milieu ultra-concurrentiel.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "senny-mayulu", name: "Senny Mayulu", number: "24", position: "Milieu de terrain", line: "Milieux", status: "Jeune à suivre", role: "Milieu polyvalent", profile: "Un Titi capable de relier les lignes sans se cacher du ballon.", watch: "Minutes en Ligue 1, progression physique et confiance du staff.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "dro-fernandez", name: "Dro Fernández", number: "27", position: "Milieu de terrain", line: "Milieux", status: "Effectif provisoire PSG 2026-2027", role: "Milieu de développement", profile: "Profil technique à observer dans la rotation et les matchs de préparation.", watch: "Place réelle dans le groupe professionnel.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "warren-zaire-emery", name: "Warren Zaïre-Emery", number: "33", position: "Milieu de terrain", line: "Milieux", status: "Symbole du projet", role: "Milieu box-to-box", profile: "Puissance, maturité et identité parisienne : il incarne la passerelle entre formation et très haut niveau.", watch: "Leadership et régularité offensive.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "joao-neves", name: "João Neves", number: "87", position: "Milieu de terrain", line: "Milieux", status: "Titulaire de très haut niveau", role: "Milieu intense et organisateur", profile: "Pressing, qualité sous pression et volume : le type de joueur qui fait respirer tout un bloc.", watch: "Gestion de la fatigue sur une saison longue.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "khvicha-kvaratskhelia", name: "Khvicha Kvaratskhelia", number: "7", position: "Attaquant", line: "Attaquants", status: "Menace offensive majeure", role: "Ailier gauche", profile: "Dribble, imprévisibilité et prise de risque permanente.", watch: "Relation avec Nuno Mendes et efficacité dans les zones décisives.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "ousmane-dembele", name: "Ousmane Dembélé", number: "10", position: "Attaquant", line: "Attaquants", status: "Star du cycle Luis Enrique", role: "Ailier créateur", profile: "Ambidextrie, vitesse et chaos contrôlé : il peut retourner un match en deux accélérations.", watch: "Leadership offensif et constance devant le but.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "desire-doue", name: "Désiré Doué", number: "14", position: "Attaquant", line: "Attaquants", status: "Talent premium", role: "Ailier ou milieu offensif", profile: "Créativité, conduite de balle et polyvalence dans les demi-espaces.", watch: "Choix dans le dernier geste et gestion de l'exposition médiatique.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "bradley-barcola", name: "Bradley Barcola", number: "29", position: "Attaquant", line: "Attaquants", status: "Ailier français majeur", role: "Ailier de profondeur", profile: "Vitesse, appels longs et capacité à étirer les blocs.", watch: "Efficacité, concurrence à gauche et réponse après les grands matchs.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "quentin-ndjantou", name: "Quentin Ndjantou", number: "47", position: "Attaquant", line: "Attaquants", status: "Jeune offensif", role: "Attaquant de développement", profile: "Profil offensif du vivier parisien, encore à stabiliser au niveau professionnel.", watch: "Utilisation en préparation, prêt éventuel ou intégration progressive.", updatedAt: "15 juillet 2026", source: "PSG.fr" },
  { id: "ibrahim-mbaye", name: "Ibrahim Mbaye", number: "49", position: "Attaquant", line: "Attaquants", status: "Jeune très surveillé", role: "Ailier", profile: "Vitesse, percussion et dossier sensible : son avenir raconte aussi la place des Titis.", watch: "Intérêt de clubs étrangers, valorisation par Paris et minutes réelles.", updatedAt: "15 juillet 2026", source: "PSG.fr" }
];

export const legendProfiles = [
  { id: "safet-susic", name: "Safet Susic", psgPeriod: "1982-1991", lifeStatus: "Vivant", currentLife: "Ancien entraîneur, figure respectée du football bosnien et mémoire technique du PSG.", role: "Meneur de jeu", profile: "L'un des joueurs les plus élégants de l'histoire parisienne, symbole du PSG artiste.", whyMatters: "Il a fixé une idée du beau jeu au Parc.", updatedAt: "15 juillet 2026" },
  { id: "mustapha-dahleb", name: "Mustapha Dahleb", psgPeriod: "1974-1984", lifeStatus: "Vivant", currentLife: "Ancienne idole du Parc, régulièrement cité parmi les pères du mythe parisien.", role: "Attaquant créateur", profile: "Technique, inspiration et attachement populaire.", whyMatters: "Il a donné au jeune PSG ses premières grandes émotions.", updatedAt: "15 juillet 2026" },
  { id: "luis-fernandez", name: "Luis Fernandez", psgPeriod: "1978-1986, puis entraîneur", lifeStatus: "Vivant", currentLife: "Consultant, homme de média et voix historique du football français.", role: "Milieu", profile: "Gamin du club, leader de combat et champion de France 1986.", whyMatters: "Il incarne le PSG populaire et formateur.", updatedAt: "15 juillet 2026" },
  { id: "bernard-lama", name: "Bernard Lama", psgPeriod: "1992-1997, 1998-2000", lifeStatus: "Vivant", currentLife: "Ancien international, engagé dans des projets sportifs et sociaux.", role: "Gardien", profile: "Gardien spectaculaire, charismatique, essentiel dans la grande période européenne des années 90.", whyMatters: "Son style a marqué une génération entière.", updatedAt: "15 juillet 2026" },
  { id: "rai", name: "Raí", psgPeriod: "1993-1998", lifeStatus: "Vivant", currentLife: "Figure publique au Brésil, engagé dans des causes sociales et éducatives.", role: "Meneur de jeu", profile: "Capitaine de la Coupe des Coupes 1996, élégance et leadership.", whyMatters: "Il reste l'un des plus grands symboles affectifs du Parc.", updatedAt: "15 juillet 2026" },
  { id: "george-weah", name: "George Weah", psgPeriod: "1992-1995", lifeStatus: "Vivant", currentLife: "Ancien président du Liberia, mandat achevé en janvier 2024.", role: "Attaquant", profile: "Puissance, vitesse et Ballon d'Or après son passage parisien.", whyMatters: "Il a donné au PSG une crédibilité mondiale avant l'ère QSI.", updatedAt: "15 juillet 2026" },
  { id: "youri-djorkaeff", name: "Youri Djorkaeff", psgPeriod: "1995-1996", lifeStatus: "Vivant", currentLife: "Ancien international français, actif dans l'écosystème du football et de sa fondation.", role: "Attaquant", profile: "Talent offensif majeur de l'équipe victorieuse en Europe.", whyMatters: "Une saison courte, mais une trace immense.", updatedAt: "15 juillet 2026" },
  { id: "ronaldinho", name: "Ronaldinho", psgPeriod: "2001-2003", lifeStatus: "Vivant", currentLife: "Ambassadeur médiatique du football spectacle, présent sur des événements internationaux.", role: "Meneur offensif", profile: "Deux ans de magie brute, parfois indisciplinée, toujours inoubliable.", whyMatters: "Il a placé Paris dans l'imaginaire mondial du football créatif.", updatedAt: "15 juillet 2026" },
  { id: "pauleta", name: "Pauleta", psgPeriod: "2003-2008", lifeStatus: "Vivant", currentLife: "Figure suivie au Portugal et régulièrement associée à la mémoire offensive du PSG.", role: "Avant-centre", profile: "Finition, fidélité et buts dans une période plus rugueuse du club.", whyMatters: "Il a porté Paris quand le club ne dominait pas encore.", updatedAt: "15 juillet 2026" },
  { id: "zlatan-ibrahimovic", name: "Zlatan Ibrahimovic", psgPeriod: "2012-2016", lifeStatus: "Vivant", currentLife: "Dirigeant/conseiller dans l'environnement de l'AC Milan et personnalité mondiale.", role: "Avant-centre", profile: "Il a imposé une mentalité de domination immédiate.", whyMatters: "Le PSG QSI a changé de ton avec lui.", updatedAt: "15 juillet 2026" },
  { id: "edinson-cavani", name: "Edinson Cavani", psgPeriod: "2013-2020", lifeStatus: "Vivant", currentLife: "Toujours actif dans le football professionnel selon les dernières données publiques connues.", role: "Avant-centre", profile: "Travail, appels, buts et relation viscérale avec les supporters.", whyMatters: "Il reste l'un des buteurs les plus aimés de l'histoire parisienne.", updatedAt: "15 juillet 2026" },
  { id: "kylian-mbappe", name: "Kylian Mbappé", psgPeriod: "2017-2024", lifeStatus: "Vivant", currentLife: "Star internationale encore en activité, après son départ du PSG.", role: "Attaquant", profile: "Meilleur buteur historique du club et machine à records.", whyMatters: "Ses chiffres ont redéfini le plafond individuel parisien.", updatedAt: "15 juillet 2026" },
  { id: "marquinhos", name: "Marquinhos", psgPeriod: "2013-", lifeStatus: "Vivant", currentLife: "Capitaine du PSG et recordman d'apparitions du club.", role: "Défenseur", profile: "Longévité, brassard, trophées et attachement à Paris.", whyMatters: "Il relie toutes les ères récentes du club.", updatedAt: "15 juillet 2026" },
  { id: "neymar", name: "Neymar", psgPeriod: "2017-2023", lifeStatus: "Vivant", currentLife: "Joueur encore actif et immense personnalité médiatique du football mondial.", role: "Attaquant créateur", profile: "Génie, blessures, débats : impossible à réduire à une seule lecture.", whyMatters: "Son arrivée a changé l'échelle mondiale du PSG.", updatedAt: "15 juillet 2026" },
  { id: "lionel-messi", name: "Lionel Messi", psgPeriod: "2021-2023", lifeStatus: "Vivant", currentLife: "Joueur encore actif, icône absolue du football mondial.", role: "Attaquant créateur", profile: "Deux saisons parisiennes très commentées, mais un impact planétaire incontestable.", whyMatters: "Sa présence a offert au PSG une visibilité sans équivalent.", updatedAt: "15 juillet 2026" },
  { id: "angel-di-maria", name: "Ángel Di María", psgPeriod: "2015-2022", lifeStatus: "Vivant", currentLife: "Joueur encore actif selon les dernières données publiques connues, idole aussi en Argentine.", role: "Ailier et passeur", profile: "Technique, passes décisives et grands matchs européens.", whyMatters: "Il a souvent été le joueur des soirs qui comptent.", updatedAt: "15 juillet 2026" },
  { id: "marco-verratti", name: "Marco Verratti", psgPeriod: "2012-2023", lifeStatus: "Vivant", currentLife: "Joueur encore actif après son départ du PSG.", role: "Milieu", profile: "Pressing, conservation et personnalité unique au milieu.", whyMatters: "Il a incarné pendant onze ans le cœur technique parisien.", updatedAt: "15 juillet 2026" },
  { id: "ousmane-dembele", name: "Ousmane Dembélé", psgPeriod: "2023-", lifeStatus: "Vivant", currentLife: "Joueur majeur du PSG actuel.", role: "Ailier", profile: "Chaos offensif, ambidextrie et influence dans le cycle Luis Enrique.", whyMatters: "Il est devenu l'une des figures du PSG champion.", updatedAt: "15 juillet 2026" },
  { id: "vitinha", name: "Vitinha", psgPeriod: "2022-", lifeStatus: "Vivant", currentLife: "Milieu central du PSG actuel.", role: "Milieu organisateur", profile: "Le tempo, la sécurité technique et la maturité dans les grands matchs.", whyMatters: "Il a transformé le PSG en équipe plus collective.", updatedAt: "15 juillet 2026" },
  { id: "achraf-hakimi", name: "Achraf Hakimi", psgPeriod: "2021-", lifeStatus: "Vivant", currentLife: "Cadre international et latéral du PSG actuel.", role: "Latéral droit", profile: "Projection, vitesse et personnalité de grand rendez-vous.", whyMatters: "Il a redonné une dimension verticale au couloir droit.", updatedAt: "15 juillet 2026" },
  { id: "warren-zaire-emery", name: "Warren Zaïre-Emery", psgPeriod: "2022-", lifeStatus: "Vivant", currentLife: "Joueur formé au club et figure du PSG actuel.", role: "Milieu", profile: "Le symbole le plus fort du lien entre centre de formation et équipe première.", whyMatters: "Son histoire donne un visage local au projet mondial.", updatedAt: "15 juillet 2026" }
];

export const seasonSquads = [
  {
    id: "2026-27",
    label: "2026-2027",
    quality: "Complet officiel provisoire",
    note: "Effectif masculin listé par PSG.fr au 15 juillet 2026.",
    groups: [
      { label: "Gardiens", players: ["Alessandro Longoni", "Lucas Chevalier", "Matvey Safonov"] },
      { label: "Défenseurs", players: ["Achraf Hakimi", "Lucas Beraldo", "Marquinhos", "Illia Zabarnyi", "Lucas Hernández", "Nuno Mendes", "Willian Pacho"] },
      { label: "Milieux", players: ["Fabián Ruiz", "Vitinha", "Kang-In Lee", "Senny Mayulu", "Dro Fernández", "Warren Zaïre-Emery", "João Neves"] },
      { label: "Attaquants", players: ["Khvicha Kvaratskhelia", "Ousmane Dembélé", "Désiré Doué", "Bradley Barcola", "Quentin Ndjantou", "Ibrahim Mbaye"] }
    ]
  },
  {
    id: "2025-26",
    label: "2025-2026",
    quality: "Groupe repère champion",
    note: "Saison historique à compléter avec archive exhaustive compatible.",
    groups: [
      { label: "Cadres du cycle", players: ["Marquinhos", "Achraf Hakimi", "Nuno Mendes", "Vitinha", "João Neves", "Ousmane Dembélé", "Bradley Barcola", "Fabián Ruiz"] },
      { label: "Jeunes et rotation", players: ["Warren Zaïre-Emery", "Senny Mayulu", "Désiré Doué", "Lucas Beraldo", "Willian Pacho"] }
    ]
  },
  {
    id: "2019-20",
    label: "2019-2020",
    quality: "Groupe repère finaliste européen",
    note: "Sélection éditoriale des joueurs majeurs de la saison, non exhaustive.",
    groups: [
      { label: "Base", players: ["Keylor Navas", "Marquinhos", "Thiago Silva", "Presnel Kimpembe", "Marco Verratti", "Idrissa Gueye"] },
      { label: "Attaque", players: ["Neymar", "Kylian Mbappé", "Ángel Di María", "Mauro Icardi", "Edinson Cavani"] }
    ]
  },
  {
    id: "2012-13",
    label: "2012-2013",
    quality: "Groupe repère bascule QSI",
    note: "Saison du retour durable au sommet national.",
    groups: [
      { label: "Cadres", players: ["Salvatore Sirigu", "Thiago Silva", "Maxwell", "Blaise Matuidi", "Marco Verratti", "Javier Pastore"] },
      { label: "Attaque", players: ["Zlatan Ibrahimovic", "Ezequiel Lavezzi", "Jérémy Ménez", "Lucas Moura"] }
    ]
  },
  {
    id: "1995-96",
    label: "1995-1996",
    quality: "Groupe repère Coupe des Coupes",
    note: "Saison européenne fondatrice, à enrichir avec archive complète.",
    groups: [
      { label: "Figures", players: ["Bernard Lama", "Alain Roche", "Paul Le Guen", "Vincent Guérin", "Raí"] },
      { label: "Attaque", players: ["Youri Djorkaeff", "Patrice Loko", "Bruno Ngotty"] }
    ]
  },
  {
    id: "1985-86",
    label: "1985-1986",
    quality: "Groupe repère premier titre",
    note: "Premier titre de champion de France, archive complète à importer.",
    groups: [
      { label: "Repères", players: ["Joël Bats", "Luis Fernandez", "Safet Susic", "Dominique Rocheteau"] },
      { label: "Mémoire", players: ["Jean-Marc Pilorget", "Thierry Morin", "Nabatingue Toko"] }
    ]
  }
];

export const newsMeta = {
  updatedAt: "2026-07-22T10:04:00+02:00",
  edition: "Édition PSG du 22 juillet 2026",
  displayDate: "22 juillet 2026",
  displayTime: "10h04",
  rightsNote: "Synthèses originales Parisien 90. Les sources sont citées et liées ; aucun article tiers n'est reproduit."
};

const withNewsDate = (date, dateLabel, items) => items.map((item) => ({ date, dateLabel, ...item }));

export const newsFeed = [
  ...withNewsDate("2026-07-22", "22 juillet 2026", [
  { id: "veille-22-juillet-source-tracker", time: "10:04", category: "Sources", title: "Veille PSG du 22 juillet : Mbaye surveillé, le fil garde ses niveaux de preuve", summary: "Contrôle effectué sur PSG.fr, L'Équipe, CulturePSG, Canal Supporters, ParisFans, Les Titis du PSG, RMC Sport et Foot Mercato. La piste AS Roma pour Ibrahim Mbaye est signalée avec réserve après recoupement de la source italienne ; aucune signature ni officialisation n'est affirmée sans annonce directe.", source: "Parisien 90 — PSG.fr, L'Équipe, CulturePSG, Canal Supporters, ParisFans, Les Titis du PSG, RMC Sport, Foot Mercato", url: "/sources-psg/", reliability: "Méthode", viral: 54 },
  ]),
  ...withNewsDate("2026-07-21", "21 juillet 2026", [
  { id: "ibrahim-mbaye-as-roma-pret-etudie", time: "08:15", category: "Mercato", title: "Ibrahim Mbaye : l'AS Roma étudie un prêt, Paris garderait la main sur son avenir", summary: "Le Corriere dello Sport avance que l'AS Roma s'intéresse à Ibrahim Mbaye et envisage un prêt avec option d'achat. ParisFans et Les Titis du PSG relaient la même source : le PSG n'a rien officialisé, et la formule comme l'issue du dossier restent à confirmer.", source: "Corriere dello Sport, relayé par ParisFans et Les Titis du PSG", url: "https://www.corrieredellosport.it/news/calcio/calcio-mercato/roma/2026/07/21-150026381/tentazione_mbaye_per_la_roma_la_formula_del_prestito_con_riscatto_e_controriscatto", reliability: "Rumeur recoupée — à confirmer", viral: 82 },
  { id: "veille-21-juillet-source-tracker", time: "07:32", category: "Sources", title: "Veille PSG du 21 juillet : pas de nouvelle officialisation, le fil garde ses réserves", summary: "Contrôle matinal effectué sur PSG.fr, L'Équipe, CulturePSG, Canal Supporters, ParisFans, RMC Sport et Foot Mercato. Les éléments consultés confirment surtout les dossiers Lucas Digne et Maghnes Akliouche déjà suivis : aucune officialisation PSG nouvelle n'est ajoutée sans source directe.", source: "Parisien 90 — PSG.fr, L'Équipe, CulturePSG, Canal Supporters, ParisFans, RMC Sport, Foot Mercato", url: "/sources-psg/", reliability: "Méthode", viral: 53 },
  ]),
  ...withNewsDate("2026-07-20", "20 juillet 2026", [
  { id: "lucas-digne-visite-medicale-validee", time: "20:17", category: "Mercato", title: "Lucas Digne : visite médicale validée selon Le Parisien, la signature reste le dernier verrou", summary: "ParisFans relaie une information du Parisien selon laquelle Lucas Digne a passé sa visite médicale avec succès ce lundi. Le latéral doit encore signer son contrat de trois ans : le transfert est très avancé, mais le PSG ne l'a pas officialisé.", source: "Le Parisien, relayé par ParisFans", url: "https://www.parisfans.fr/une/mercato-lucas-digne-a-passe-sa-visite-medicale-pour-signer-au-psg-927154.html", reliability: "Fort — en attente d'officialisation", viral: 98 },
  { id: "lucas-digne-accord-total-visite-medicale", time: "14:42", category: "Mercato", title: "Lucas Digne au PSG : accord total annoncé, la visite médicale doit ouvrir la dernière ligne droite", summary: "L'Équipe annonce que le PSG a levé la clause de Lucas Digne à Aston Villa et qu'une visite médicale doit intervenir dans les prochaines heures, avant un contrat de trois ans. Une avancée très forte, mais pas encore une officialisation du club parisien.", source: "L'Équipe", url: "https://www.lequipe.fr/Football/Actualites/Mercato-accord-total-pour-lucas-digne-au-psg-qui-va-passer-sa-visite-medicale/1705911", reliability: "Fort — en attente d'officialisation", viral: 97 },
  { id: "veille-20-juillet-source-tracker", time: "15:32", category: "Sources", title: "Veille PSG du 20 juillet : Parisien 90 poursuit le recoupement des sources", summary: "Contrôle effectué sur PSG.fr, L'Équipe, CulturePSG et Canal Supporters après la mise à jour du 19 juillet au soir. Le calendrier officiel confirme les rendez-vous déjà suivis ; le fil ne retient les mouvements mercato qu'avec une source directe et un niveau de preuve clairement affiché.", source: "Parisien 90 — PSG.fr, L'Équipe, CulturePSG, Canal Supporters", url: "/sources-psg/", reliability: "Méthode", viral: 52 },
  ]),
  ...withNewsDate("2026-07-19", "19 juillet 2026", [
  { id: "akliouche-monaco-accord-proche-soiree", time: "19:12", category: "Mercato", title: "Akliouche au PSG : l'accord avec Monaco se rapproche enfin, Paris tient son accélération du soir", summary: "Canal Supporters annonce un accord très proche entre le PSG et Monaco pour Maghnes Akliouche, tandis que ParisFans décrit lui aussi un net rapprochement. Ce n'est toujours pas une signature officielle, mais le dossier a clairement changé de vitesse depuis la matinée.", source: "Canal Supporters / ParisFans", url: "https://canal-supporters.com/un-accord-tres-proche-detre-trouve-entre-le-psg-et-monaco-pour-akliouche/", reliability: "Rumeur solide", viral: 96 },
  { id: "akliouche-monaco-refus-troisieme-offre", time: "10:55", category: "Mercato", title: "Akliouche au PSG : Monaco dit encore non, mais le dossier sent la semaine décisive", summary: "Canal Supporters rapporte un troisième refus monégasque, tout en indiquant que le joueur veut Paris et que les positions se rapprochent. C'est le type de feuilleton qui peut basculer très vite, mais il reste une négociation, pas une officialisation.", source: "Canal Supporters", url: "https://canal-supporters.com/las-monaco-aurait-refuse-une-troisieme-offre-du-psg-pour-akliouche/", reliability: "Rumeur solide", viral: 93 },
  { id: "barcola-arsenal-liverpool-attente", time: "10:35", category: "Mercato", title: "Barcola, le faux calme : Arsenal ne bouge pas, Liverpool attend le prix", summary: "Foot01 relaie la mise au point de Fabrizio Romano : pas de nouveau contact Arsenal avec le clan Barcola ou le PSG après le dossier Morgan Rogers, mais Liverpool reste à l'affût si le prix devient jouable. Paris tient la clé.", source: "Foot01 / Fabrizio Romano", url: "https://www.foot01.com/paris/psg-le-dossier-barcola-relance-par-un-transfert-a-138me", reliability: "À suivre", viral: 88 },
  { id: "kolo-muani-juventus-ecart-prix", time: "10:12", category: "Mercato", title: "Kolo Muani-Juve : le dossier avance, mais l'écart de prix raconte tout le bras de fer", summary: "La Juventus veut toujours Randal Kolo Muani, mais plusieurs sources italiennes évoquent un écart important avec Paris. Le PSG veut vendre, la Juve veut patienter : parfait pour un poker menteur estival.", source: "Black & White & Read All Over", url: "https://www.blackwhitereadallover.com/juventus-transfer-rumors-news/40039/juventus-striker-hunt-randal-kolo-muani-mateo-pellegrino-2026-serie-a-summer-transfer-rumors", reliability: "Rumeur recoupée", viral: 84 },
  { id: "nsoki-dinamo-zagreb-choix", time: "09:48", category: "Titis", title: "Nsoki choisit Zagreb : le Titi veut jouer, Paris doit encore négocier", summary: "Les Titis du PSG, citant L'Équipe, indiquent que Noah Nsoki a choisi le Dinamo Zagreb. Le point important : l'accord avec le PSG n'est pas encore trouvé. Départ probable, mais pas encore bouclé.", source: "Les Titis du PSG / L'Équipe", url: "https://www.lestitisdupsg.fr/a-la-une/%F0%9F%97%9E%EF%B8%8Fnews-formation-noah-nsoki-a-choisi-le-dinamo-zagreb-lequipe/", reliability: "Fort — accord club à trouver", viral: 79 },
  { id: "france-angleterre-parisiens-buts", time: "09:22", category: "Sélections", title: "France-Angleterre 4-6 : les Parisiens marquent, les Bleus explosent quand même", summary: "CulturePSG détaille une petite finale folle : Mbappé, Barcola et Dembélé apparaissent dans le résumé des buts français, mais l'Angleterre repart avec la troisième place. Paris brille individuellement, la France prend le choc collectivement.", source: "CulturePSG", url: "https://www.culturepsg.com/news/coupe-du-monde-2026/france-angleterre-le-resume-et-les-buts-en-video/60145", reliability: "Fort", viral: 86 },
  { id: "kouassi-lille-officiel-ancien", time: "08:58", category: "Anciens", title: "Tanguy Kouassi au LOSC : l'ancien pari parisien revient en Ligue 1", summary: "L'Équipe indique que Tanguy Kouassi s'est engagé avec Lille pour deux ans plus une année optionnelle après son départ de Séville. Un ancien Titi revient dans le championnat où son choix de quitter Paris avait tant fait parler.", source: "L'Équipe", url: "https://www.lequipe.fr/Football/Actualites/Le-losc-officialise-l-arrivee-du-defenseur-central-tanguy-kouassi-pour-deux-ans/1705449", reliability: "Officiel", viral: 68 },
  { id: "u19-reprise-campus-psg", time: "08:31", category: "Formation", title: "Les U19 reprennent au Campus : la machine à former repart, et c'est stratégique", summary: "PSG.fr a publié la reprise des U19 au Campus le 18 juillet. Ce n'est pas une rumeur brillante de mercato, mais c'est un signal de fond : Paris doit produire, pas seulement acheter.", source: "PSG.fr", url: "https://www.psg.fr/content/la-reprise-des-u19-en-images-campus-psg-centre-de-formation-entrainement-2026-2027", reliability: "Officiel", viral: 61 },
  { id: "veille-19-juillet-source-tracker", time: "08:05", category: "Sources", title: "Veille du 19 juillet : le mercato s'agite, mais Parisien 90 garde les niveaux de preuve visibles", summary: "La revue matinale croise PSG.fr, CulturePSG, Canal Supporters, Foot01, Les Titis du PSG, L'Équipe et agrégateurs spécialisés. Les dossiers chauds sont Akliouche, Barcola, Kolo Muani et les jeunes au départ.", source: "Parisien 90, sources liées dans le fil", url: "/sources-psg/", reliability: "Méthode", viral: 57 },
  ]),
  ...withNewsDate("2026-07-16", "16 juillet 2026", [
  { id: "pre-saison-majorque-united-2026", time: "14:30", category: "Calendrier", title: "Majorque puis Manchester United : la préparation du PSG prend forme", summary: "PSG.fr liste deux amicaux avant Lens : déplacement à Majorque le 5 août, puis Manchester United à Göteborg le 8 août. Deux tests officiels, à lire séparément du calendrier de Ligue 1.", source: "PSG.fr", url: "https://www.psg.fr/football-masculin/calendrier/season/2026-27?competition=Club_Friendlies", reliability: "Officiel", viral: 82 },
  { id: "lens-psg-trophee-2026", time: "12:33", category: "Calendrier", title: "Lens-PSG au Trophée des champions : le premier rendez-vous officiel est posé", summary: "Le PSG affiche Lens-Paris le 16 août au stade Bollaert-Delelis, en finale du Trophée des champions. L'horaire reste volontairement à confirmer : deux pages officielles du club consultées indiquent 18h45 et 20h45.", source: "PSG.fr", url: "https://www.psg.fr/matchs/football-masculin/20262027/lens-vs-paris-2026-08-16", reliability: "Officiel — horaire à confirmer", viral: 77 },
  ]),
  ...withNewsDate("2026-07-15", "15 juillet 2026", [
  { id: "digne-retour-psg", time: "18:32", category: "Mercato", title: "Digne au PSG : le transfert malin qui va quand même énerver du monde", summary: "Paris veut verrouiller une doublure fiable derrière Nuno Mendes. Sur le terrain, c'est cohérent. Dans le débat public, ça ressemble déjà à une petite bombe de mercato.", source: "L'Équipe / CulturePSG", url: "https://www.lequipe.fr/Football/Actualites/Mercato-lucas-digne-va-signer-au-paris-saint-germain-apres-la-coupe-du-monde-et-faire-son-retour-dans-la-capitale/1704076", reliability: "Fort", viral: 94 },
  { id: "mbaye-dortmund", time: "18:05", category: "Titis", title: "Mbaye regardé par Dortmund : Paris peut-il vraiment laisser filer ce signal ?", summary: "L'intérêt allemand donne une autre dimension au dossier. Si Paris vend, il vendra cher, mais le sujet dépasse le chèque : c'est la crédibilité de la filière jeunes qui revient sur la table.", source: "CulturePSG", url: "https://www.culturepsg.com/news/mercato/un-club-allemand-a-l-affut-pour-mbaye/60123", reliability: "Rumeur solide", viral: 91 },
  { id: "mbemba-paris-fc", time: "17:42", category: "Formation", title: "Mbemba vers le Paris FC : le voisin parisien n'attend plus la permission", summary: "Le défenseur formé au PSG se dirige vers le Paris FC. Symboliquement, c'est fort : la capitale devient un marché interne, et les Titis ont désormais plusieurs vitrines.", source: "L'Équipe", url: "https://www.lequipe.fr/Football/Actualites/Mercato-le-jeune-defenseur-du-psg-emmanuel-mbemba-va-signer-au-paris-fc/1704270", reliability: "Fort", viral: 88 },
  { id: "diomande-leipzig", time: "17:18", category: "Mercato", title: "Diomande, le dossier qui sent le bras de fer à 100 M€", summary: "Leipzig garde la main et Paris n'est pas seul. Dossier spectaculaire, mais à traiter froidement : le prix peut transformer une bonne idée en piège.", source: "CulturePSG", url: "https://www.culturepsg.com/news/mercato/diomande-n-aurait-pas-dit-oui-qu-au-psg/60124", reliability: "À suivre", viral: 84 },
  { id: "fabian-finale", time: "16:55", category: "Sélections", title: "Fabián Ruiz en finale : même loin de Paris, le PSG reste dans la lumière", summary: "La France des Parisiens s'arrête, mais Fabián Ruiz poursuit sa route. Pour Paris, le Mondial raconte aussi la densité internationale du vestiaire.", source: "PSG.fr", url: "https://www.psg.fr/content/fin-de-parcours-pour-les-bleus-lespagne-de-fabian-ruiz-en-finale-coupe-du-monde-fifa-2026-paris-saint-germain", reliability: "Officiel", viral: 72 },
  { id: "nsoki-croatie", time: "16:21", category: "Titis", title: "Nsoki vers la Croatie : encore un jeune qui cherche le couloir de sortie", summary: "La piste Dinamo Zagreb est à surveiller. Ce n'est pas le transfert le plus bruyant, mais c'est typiquement le genre de mouvement qui nourrit le débat sur les débouchés au PSG.", source: "ParisFans", url: "https://www.parisfans.fr/une/mercato-un-titi-du-psg-vers-la-croatie-927390.html", reliability: "À vérifier", viral: 67 },
  { id: "abo-el-nay-rio-ave", time: "15:58", category: "Formation", title: "Abo El Nay plaît au Portugal : le marché des Titis s'active partout", summary: "Rio Ave s'intéresse au jeune parisien. Là encore, Paris doit arbitrer entre développement, contrat et timing sportif.", source: "L'Équipe", url: "https://www.lequipe.fr/Football/Actualites/Le-club-portugais-rio-ave-s-interesse-au-titi-du-psg-rayan-abo-el-nay/1704188", reliability: "Fort", viral: 63 },
  { id: "calendrier-rennes", time: "15:22", category: "Calendrier", title: "PSG-Rennes ouvrira la Ligue 1 parisienne : première soirée test au Parc", summary: "Le calendrier 2026-2027 place Rennes au Parc dès la première journée. Une affiche parfaite pour lancer le récit : champion attendu, adversaire immédiatement crédible.", source: "PSG.fr", url: "https://www.psg.fr/football-masculin/calendrier/season/2026-27?competition=Ligue_1", reliability: "Officiel", viral: 76 },
  { id: "classique-septembre", time: "15:01", category: "Calendrier", title: "Le premier Classique tombe vite : Marseille-PSG le 20 septembre", summary: "Le calendrier ne laisse pas Paris respirer longtemps. Le Vélodrome arrive dès la cinquième journée : premier thermomètre populaire de la saison.", source: "PSG.fr", url: "https://www.psg.fr/football-masculin/calendrier/season/2026-27?competition=Ligue_1", reliability: "Officiel", viral: 90 },
  { id: "classique-retour", time: "14:44", category: "Calendrier", title: "PSG-OM au Parc en février : la date que tout le monde va encercler", summary: "Le Classique retour est prévu le 7 février 2027. Selon l'état du championnat et de l'Europe, ce match peut devenir un accélérateur narratif énorme.", source: "PSG.fr", url: "https://www.psg.fr/football-masculin/calendrier/season/2026-27?competition=Ligue_1", reliability: "Officiel", viral: 89 },
  { id: "paris-fc-derby", time: "14:12", category: "Calendrier", title: "Paris FC au programme : le derby parisien devient un vrai contenu premium", summary: "Deux rendez-vous contre le Paris FC sont au calendrier. Pour le PSG, l'enjeu est sportif, mais aussi territorial : qui raconte Paris au football ?", source: "PSG.fr", url: "https://www.psg.fr/football-masculin/calendrier/season/2026-27?competition=Ligue_1", reliability: "Officiel", viral: 82 },
  { id: "effectif-officiel", time: "13:53", category: "Effectif", title: "L'effectif provisoire PSG 26/27 compte 23 joueurs listés", summary: "PSG.fr affiche 23 joueurs dans l'effectif masculin provisoire. Le groupe est jeune, dense derrière et très chargé au milieu.", source: "PSG.fr", url: "https://www.psg.fr/football-masculin/effectif", reliability: "Officiel", viral: 78 },
  { id: "staff-luis-enrique", time: "13:35", category: "Staff", title: "Luis Enrique garde une structure de staff très identifiable", summary: "Autour de l'entraîneur, PSG.fr liste adjoints, performance, gardiens et psychologie. La stabilité du staff est un avantage compétitif souvent sous-estimé.", source: "PSG.fr", url: "https://www.psg.fr/football-masculin/staff", reliability: "Officiel", viral: 62 },
  { id: "zabarnyi-signal", time: "13:04", category: "Effectif", title: "Zabarnyi dans le groupe : Paris muscle encore sa défense centrale", summary: "La présence d'Illia Zabarnyi dans l'effectif provisoire confirme la densité défensive. Paris ne veut pas seulement attaquer fort : il veut survivre aux mois sales.", source: "PSG.fr", url: "https://www.psg.fr/football-masculin/effectif", reliability: "Officiel", viral: 69 },
  { id: "chevalier-safonov", time: "12:42", category: "Effectif", title: "Chevalier-Safonov : la hiérarchie des gardiens devient un sujet à part entière", summary: "Avec Lucas Chevalier et Matvey Safonov listés, le poste de gardien est ouvert à une vraie bataille sportive. Paris n'aura pas le droit à l'ambiguïté trop longtemps.", source: "PSG.fr", url: "https://www.psg.fr/football-masculin/effectif", reliability: "Officiel", viral: 66 },
  { id: "doué-mayulu-wze", time: "12:18", category: "Jeunes", title: "Doué, Mayulu, Zaïre-Emery : le PSG doit prouver que jeunesse et domination cohabitent", summary: "Le groupe parisien a assez de talents jeunes pour éviter le mercato réflexe. Reste la vraie question : combien joueront quand la saison brûlera ?", source: "Analyse Parisien 90, base PSG.fr", url: "https://www.psg.fr/football-masculin/effectif", reliability: "Analyse", viral: 79 },
  { id: "barcola-concurrence", time: "11:55", category: "Effectif", title: "Barcola face à Kvaratskhelia et Dembélé : concurrence de luxe ou embouteillage ?", summary: "Paris a une ligne offensive explosive. Pour Barcola, l'enjeu n'est pas seulement de jouer : c'est de rester décisif quand les places deviennent rares.", source: "Analyse Parisien 90, base PSG.fr", url: "https://www.psg.fr/football-masculin/effectif", reliability: "Analyse", viral: 83 },
  { id: "vitinha-joao-neves", time: "11:31", category: "Tactique", title: "Vitinha-João Neves : le double moteur qui peut étouffer la Ligue 1", summary: "Quand ces deux-là contrôlent le rythme, Paris peut défendre en gardant le ballon. C'est moins spectaculaire qu'un dribble, mais souvent plus violent pour l'adversaire.", source: "Analyse Parisien 90, base PSG.fr", url: "https://www.psg.fr/football-masculin/effectif", reliability: "Analyse", viral: 74 },
  { id: "nuno-digne-debat", time: "11:06", category: "Mercato", title: "Digne derrière Nuno Mendes : ce n'est pas sexy, c'est peut-être exactement le besoin", summary: "Les très grands clubs gagnent aussi avec des doublures fiables. Le débat va être émotionnel, mais le besoin de rotation à gauche est réel.", source: "Analyse Parisien 90", url: "https://www.culturepsg.com/news/mercato/le-psg-a-boucle-l-inattendu-retour-de-digne/60110", reliability: "Analyse", viral: 80 },
  { id: "ligue1-sans-semaine", time: "10:44", category: "Calendrier", title: "Ligue 1 sans journée en semaine : bonne nouvelle pour le PSG européen", summary: "Le calendrier général annonce aucune journée de Ligue 1 en semaine. Pour un PSG qui vise tout, c'est une donnée clé dans la gestion de la fatigue.", source: "PSG.fr / LFP", url: "https://www.psg.fr/content/le-calendrier-general-des-competitions-2026-2027-devoile-psg-ligue-1-lfp-2025-2026", reliability: "Officiel", viral: 64 },
  { id: "lens-reprise", time: "10:18", category: "Calendrier", title: "Reprise à Lens le 3 janvier : pas exactement une promenade digestive", summary: "Bollaert juste après la coupure, c'est le genre de rendez-vous où un champion peut perdre trois points et beaucoup de tranquillité.", source: "PSG.fr", url: "https://www.psg.fr/football-masculin/calendrier/season/2026-27?competition=Ligue_1", reliability: "Officiel", viral: 71 },
  { id: "lyon-mai", time: "09:52", category: "Calendrier", title: "Lyon-PSG en mai : un piège tardif dans le sprint final", summary: "Le déplacement au Groupama Stadium tombe à la 31e journée. S'il y a course au titre, cette date peut peser lourd.", source: "PSG.fr", url: "https://www.psg.fr/football-masculin/calendrier/season/2026-27?competition=Ligue_1", reliability: "Officiel", viral: 73 },
  { id: "histoire-cycle", time: "09:26", category: "Histoire", title: "Le PSG 2026 ne se raconte plus comme le PSG d'avant", summary: "Double champion d'Europe dans notre ligne éditoriale actuelle, Paris change de catégorie narrative : il ne cherche plus la validation, il défend un trône.", source: "Analyse Parisien 90", url: "/histoire-psg/", reliability: "Analyse", viral: 86 },
  { id: "droits-sources", time: "09:00", category: "Sources", title: "Notre règle éditoriale : citer, réécrire, lier, ne pas aspirer", summary: "Parisien 90 doit grossir vite sans se mettre en risque. Les articles tiers sont utilisés comme sources citées, jamais comme contenus repris en bloc.", source: "Parisien 90", url: "/droits-disclaimer/", reliability: "Méthode", viral: 58 }
  ])
];
